name: HaptLangExample
options:
  bundleIdPrefix: com.minhquan
  deploymentTarget:
    iOS: "14.0"
  xcodeVersion: "15.0"

packages:
  HaptLang:
    path: ../..

targets:
  HaptLangExample:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
    dependencies:
      - package: HaptLang
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.minhquan.HaptLangExample
        SWIFT_VERSION: "5.0"
